"""add reservation owner

Revision ID: 174f919a0ab1
Revises: fb7ebccdb60c
Create Date: 2024-05-31 23:33:20.953344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174f919a0ab1'
down_revision: Union[str, None] = 'fb7ebccdb60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('owner', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'reservations', 'users', ['owner'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'owner')
    # ### end Alembic commands ###
