"""add token

Revision ID: a93e62bb1ac2
Revises: 4372ccedfe6f
Create Date: 2024-05-05 12:14:11.761979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93e62bb1ac2'
down_revision: Union[str, None] = '4372ccedfe6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('token'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
